import {PROJECTS,CASES,TABS,ALIASES,SOURCE_CARDS} from './catalog.js';
import {CASE_STUDIES} from './case-studies.js';
import {ALGORITHM_GUIDES} from './algorithm-guides.js';
import {ENGINES,DEFAULTS,MODEL_NAMES,BOROUGHS} from '../projects/engine.mjs';
import {bootstrap,bike,toCSV,validateSubmission} from './engine.mjs';
import {protocolPanel,learningPanel,primarySubmission,primaryEvaluation,mountLearning} from './project-learning.js';
import {mountComparisons} from './comparison-ui.js';
import {renderCaseStudy,handleCaseStudyAction} from './case-reader.js';
const $=s=>document.querySelector(s),main=$('#content'),KEY='traffic-chapter-projects-v2';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=x=>typeof x==='number'?x.toLocaleString('zh-CN',{maximumFractionDigits:2}):esc(x??'无');
const ul=a=>`<ul>${a.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;
const href=(p,tab='overview')=>`#project/${typeof p==='string'?p:p.id}/${tab}`;
let token=0,current=null,currentTab='',data=null,analysis=null,timer=null,files=null,storageOK=true;
const cache=new Map(),configs=new Map();let state={projects:{},caseNotes:{}};
try{const s=JSON.parse(localStorage.getItem(KEY)||'null');if(s?.projects&&typeof s.projects==='object')for(const p of PROJECTS){const r=s.projects[p.id];if(r)state.projects[p.id]={started:r.started===true,notes:Array.from({length:4},(_,i)=>String(r.notes?.[i]||'').slice(0,20000)),report:String(r.report||'').slice(0,200000),history:Array.isArray(r.history)?r.history.slice(-10).filter(x=>typeof x?.time==='string'&&x?.metrics&&typeof x.metrics==='object'):[]};}if(s?.caseNotes)for(const c of CASES)state.caseNotes[c.id]=String(s.caseNotes[c.id]||'').slice(0,20000);}catch{storageOK=false;$('#storage-warning').hidden=false;}
function record(p){return state.projects[p.id]??(state.projects[p.id]={started:false,notes:['','','',''],report:'',history:[]});}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{storageOK=false;$('#storage-warning').hidden=false;}}
async function get(path,kind='json'){const key=kind+path;if(!cache.has(key))cache.set(key,fetch(path).then(r=>{if(!r.ok)throw Error(`文件读取失败（${r.status}）：${path}`);return kind==='json'?r.json():r.text();}).catch(e=>{cache.delete(key);throw e;}));return cache.get(key);}
async function projectData(p){if(p.engine==='design')return null;return get(['inference','bike'].includes(p.engine)?`chapters/data/${p.file}.json`:`projects/data/${p.file}.json`);}
function stop(){clearInterval(timer);timer=null;}
function cover(p){return `<div class="cover" style="--accent:${p.color}" aria-hidden="true"><span class="cover-number">${String(p.chapter).padStart(2,'0')}</span><svg viewBox="0 0 260 130"><path d="M-10 102 L82 102 Q112 102 112 74 L112 -10 M-10 116 L94 116 Q129 116 129 78 L129 -10 M154 144 L154 67 Q154 44 180 44 L270 44 M169 144 L169 76 Q169 61 186 61 L270 61" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="112" cy="51" r="5" fill="currentColor"/><circle cx="206" cy="61" r="5" fill="currentColor"/></svg><small>${p.level}</small></div>`;}
function sidebar(){const hash=location.hash;$('#sidebar').innerHTML=`<a class="brand" href="#projects"><span>交</span><strong>交通数据挖掘<small>开放实践课程</small></strong></a><a class="side-link ${hash.includes('case')?'':'active'}" href="#projects">章节实践 <span>08</span></a><a class="side-link ${hash.includes('case')?'active':''}" href="#cases">案例库 <span>16</span></a><div class="sidebar-label">教材章节</div><nav>${PROJECTS.map(p=>`<a class="chapter-link ${current?.id===p.id?'active':''}" href="${href(p)}" ${current?.id===p.id?'aria-current="page"':''}><span>${String(p.chapter).padStart(2,'0')}</span><div>${p.chapterName}</div></a>`).join('')}</nav><div class="side-bottom"><a href="chapter-01/">第一章交互课堂 ↗</a><a href="chapter-02/">第二章交互课堂 ↗</a><small>学习与交流，不设奖金与商业报名。</small></div>`;}
function projectCard(p){return `<article class="project-card">${cover(p)}<div><div class="card-meta">第${p.chapter}章 · ${p.chapterName}</div><h2><a href="${href(p)}">${p.title}</a></h2><p>${p.subtitle}</p><div class="tags"><span>${p.dataset}</span><span>${p.time}</span></div></div><a class="arrow-link" aria-label="进入${p.title}" href="${href(p)}">→</a></article>`;}
function caseCard(c){const g=ALGORITHM_GUIDES[c.id];return `<article class="case-card"><div class="card-meta">第${c.chapter}章 <span>${c.type}</span></div><h3><a href="#case/${c.id}">${c.title}</a></h3><p>${c.lead}</p>${g?`<p class="tiny">本章算法：${esc(g.title)}</p>`:''}<a class="text-link" href="#case/${c.id}">阅读研究全文 →</a></article>`;}
function home(query=''){
 const q=query.toLowerCase(),projects=PROJECTS.filter(p=>[p.title,p.chapterName,p.subtitle,p.dataset].join(' ').toLowerCase().includes(q)),cases=CASES.filter(c=>[c.title,c.lead,c.type,...CASE_STUDIES[c.id].keywords,CASE_STUDIES[c.id].abstract,ALGORITHM_GUIDES[c.id]?.title,ALGORITHM_GUIDES[c.id]?.sections].join(' ').toLowerCase().includes(q));
 main.innerHTML=query?`<section class="page-intro"><p class="eyebrow">搜索结果</p><h1>“${esc(query)}”</h1><p>${projects.length}个项目 · ${cases.length}个案例</p></section><div class="project-list">${projects.map(projectCard).join('')}</div><div class="case-grid">${cases.map(caseCard).join('')}</div>${!projects.length&&!cases.length?'<p class="empty">没有匹配内容，请试试“回归”“轨迹”等主题词。</p>':''}`:`<section class="page-intro"><p class="eyebrow">交通数据挖掘 · 开放教学项目</p><h1>八章教材，八个实践项目。</h1><p>从一个清晰的交通问题出发。阅读任务，探索真实数据，运行基线，提交你的分析。</p><div class="intro-links"><a class="button" href="${href('ch01')}">从第一章开始</a><a class="button outline" href="#cases">先看案例</a><span>中文任务书 · 数据与代码开放 · 无需注册</span></div></section><section><div class="section-heading"><h2>章节项目</h2><span>1章对应1个项目 · 按教材顺序学习</span></div><div class="project-list">${PROJECTS.map(projectCard).join('')}</div></section><section class="home-cases"><div class="section-heading"><div><p class="eyebrow">交通运输工程 · 研究案例</p><h2>从交通问题到研究结论</h2></div><a href="#cases">查看全部16个案例 →</a></div><div class="case-grid">${[CASES[2],CASES[6],CASES[10]].map(caseCard).join('')}</div></section>`;
}
function aside(p){return `<aside class="project-aside"><div><h3>所属章节</h3><p>第${p.chapter}章 ${p.chapterName}</p></div><div><h3>实践方式</h3><p>个人或小组 · 开放学习<br>建议 ${p.time}</p></div><div><h3>评价方式</h3><p>${p.metric}</p></div><div><h3>最终交付</h3>${ul(p.deliverables)}</div><div><h3>教学范围</h3><p>${p.sections}</p></div><a class="button outline full" href="chapters/chapter-projects.zip" download>下载八章资料包</a><p class="tiny">任务书、数据、8份工作本、参考代码与许可。各章不要求覆盖教材中的每一种方法。</p></aside>`;}
function heading(p,tab){return `<div class="breadcrumbs"><a href="#projects">章节实践</a><span>/</span><span>第${p.chapter}章</span></div><header class="project-header"><div><p class="eyebrow">开放教学项目 · ${p.level} · 按课时推进</p><h1>${p.title}</h1><p>${p.subtitle}</p><div class="tags"><span>${p.dataset}</span><span>${p.metric}</span></div></div>${cover(p)}<a class="button header-submit" href="${href(p,'submission')}">提交与自测</a></header><nav class="tabs" aria-label="项目栏目">${TABS.map(([id,label])=>`<a href="${href(p,id)}" ${tab===id?'aria-current="page" class="selected"':''}>${label}${id==='cases'?'<span>2</span>':''}</a>`).join('')}</nav>`;}
function overview(p){const r=record(p);return `${protocolPanel(p)}<h2>项目概述</h2><div class="notice neutral">这是课程实践，不是商业竞赛。按“理解问题 → 数据与代码 → 对照分析 → 提交成果”的顺序完成。</div><section class="article-section"><h3>你要解决什么问题？</h3><p class="question">${p.question}</p><p>${p.commission}</p></section><section class="article-section"><h3>从这里开始</h3><p>先阅读数据口径和分析边界，再运行参考代码。将默认结果作为起点，完成自己的对照与解释。</p><div class="actions"><button id="start">${r.started?'继续学习':'开始项目'}</button><a href="${href(p,'data')}">查看数据</a><a href="${href(p,'cases')}">阅读本章案例</a></div>${r.started?'<p class="tiny">已加入本机学习记录，不代表完成或通过验收。</p>':''}</section><section class="article-section"><h3>四个阶段任务</h3><div class="task-list">${p.tasks.map(([title,prompt,deliver],i)=>`<details class="task" ${i===0?'open':''}><summary><span>${i+1}</span>${title}</summary><p>${prompt}</p><p><strong>阶段交付：</strong>${deliver}</p><label>我的分析与证据<textarea data-note="${i}" maxlength="20000" placeholder="写出你的判断、数据依据与下一步。">${esc(r.notes[i])}</textarea></label></details>`).join('')}</div><p class="tiny" id="draft-status">分析记录仅保存在本机。提交页可以导出项目报告。</p></section><section class="article-section"><h3>先明确这些边界</h3>${ul(p.boundaries)}</section>`;}
const fields={id:'记录唯一标识；须原样保留，用于对齐结果',scenario:'交通问题情境',dataset:'数据源名称',observations:'直接观测到的对象和变量',coverage:'时间、空间或样本范围',limits:'不能由该数据直接支持的结论',source_url:'官方来源链接',local_time:'本地小时标签，未恢复夏令时',volume:'断面小时交通量，辆/小时',raw_multiplicity:'该小时在原始文件中出现的行数',date_time:'原始本地日期与时间',traffic_volume:'断面小时交通量，辆/小时',holiday:'原始节假日标签（单车数据为0/1）',temp:'原始交通量表为K；单车表为归一化气温，见原始说明',rain_1h:'过去1小时降雨量，mm',snow_1h:'过去1小时降雪量，mm',clouds_all:'云量百分比',weather_main:'天气大类',weather_description:'详细天气描述',date:'日期',day_type:'平日/周末；平日不剔除节假日',peak_mean:'07、08、09时交通量的均值，辆/小时',dteday:'日期，用于时间切分，不直接输入参考模型',cnt:'总租借次数/小时，目标标签',season:'季节类别，1至4',mnth:'月份，1至12',hr:'小时，0至23',weekday:'星期编码，0为周日',workingday:'非周末且非节假日为1',weathersit:'天气类别，1至4；原始说明定义严重程度',atemp:'归一化体感温度',hum:'相对湿度除以100',windspeed:'风速除以67',borough:'行政区，保留未知或特殊分区',latitude:'纬度，十进制度',longitude:'经度，十进制度',injured:'该事故记录伤者人数',killed:'该事故记录死亡人数',valid_coordinates:'是否通过本项目坐标边界检查',hour:'小时，0至23',count:'日期—行政区—小时的保留上车记录数',track_id:'源数据轨迹标识，不代表新的检测器识别结果',timestamp_ms:'相对时间，毫秒',x:'地面x坐标，米',y:'地面y坐标，米',agent_type:'车辆或非机动车类别'};
function table(columns,rows,limit=12){return `<div class="table-scroll"><table><thead><tr>${columns.map(x=>`<th scope="col">${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,limit).map(r=>`<tr>${r.map(v=>`<td>${fmt(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${rows.length>limit?`<p class="tiny">显示前${limit}行，共${rows.length}行；下载或导出可查看完整结果。</p>`:''}`;}
function dataTab(p){const resource=files[p.id];return `<div class="section-heading"><h2>数据说明</h2><a class="button outline" href="chapters/chapter-projects.zip" download>下载资料包</a></div><p>${p.source.details||p.dataset}。所有练习数据均保留来源与处理说明；快照固定，官网后续修订可能产生不同结果。</p><p><a href="${p.source.url}" target="_blank" rel="noopener">官方来源：${p.source.title} ↗</a></p><div class="notice">${p.source.license}${p.id==='ch04'||p.id==='ch06'?'。测试标签为公开教学自测资源，不是服务器端隐藏答案。':''}</div><section class="article-section"><h3>文件资源</h3><div class="file-list">${resource.files.map((f,i)=>`<button class="file-choice ${i===0?'selected':''}" data-file="${i}"><span class="file-icon">CSV</span><span><strong>${f.name}</strong><small>${f.role} · ${fmt(f.rows)}行 · ${(f.bytes/1024).toFixed(0)}KB</small></span></button>`).join('')}</div><div id="file-preview"></div></section><section class="article-section"><h3>数据使用约定</h3>${ul(p.boundaries)}<a href="chapters/DATA_SOURCES.md">完整来源、哈希与许可说明</a>${p.id==='ch04'?' · <a href="chapters/data/BIKE_README.txt">UCI字段原始说明</a>':''}${p.id==='ch08'?' · <a href="projects/data/SIND-LICENSE.txt">SinD原始许可</a>':''}</section>`;}
function preview(p,index){const f=files[p.id].files[index];$('#file-preview').innerHTML=`<div class="file-preview-head"><div><h3>${f.name}</h3><p>${f.note}</p></div><a href="${f.path}" download>下载文件 ↓</a></div><p class="tiny">${fmt(f.rows)}行 · ${f.columns.length}列 · 下面仅预览原文件前6行</p>${table(f.columns,f.preview)}<details class="dictionary"><summary>字段含义与文件校验</summary>${table(['字段','含义'],f.columns.map(c=>[c,fields[c]||'请查阅官方字段定义。']),99)}<p class="tiny">SHA-256：<code>${f.sha256}</code></p></details>`;document.querySelectorAll('[data-file]').forEach(b=>b.classList.toggle('selected',+b.dataset.file===index));}
const select=(name,label,options,value)=>`<label>${label}<select name="${name}">${options.map(x=>{const [v,n]=Array.isArray(x)?x:[x,x];return `<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(n)}</option>`;}).join('')}</select></label>`;
const number=(name,label,min,max,step,value)=>`<label>${label}<input type="number" name="${name}" min="${min}" max="${max}" step="${step}" value="${value}" required></label>`;
function config(p){if(!configs.has(p.id))configs.set(p.id,p.engine==='inference'?{n:'60',repetitions:'500',seed:'42',group:'all'}:p.engine==='bike'?{model:'ridge',period:'all'}:{...DEFAULTS[p.engine]});return configs.get(p.id);}
function controls(p){const c=config(p);if(p.engine==='inference')return select('n','抽样日期数',['20','60','90'],c.n)+select('repetitions','重采样次数',['200','500','1000'],c.repetitions)+select('group','日期类型',[['all','全部日期'],['weekday','周一至周五'],['weekend','周六、周日']],c.group)+number('seed','随机种子',0,4294967295,1,c.seed);
 if(p.engine==='bike')return select('model','模型',[['mean','训练期均值'],['ridge','岭回归'],['poisson','泊松回归']],c.model)+select('period','测试时段',[['all','全天'],['night','夜间22—05时'],['day','白天06—21时']],c.period);
 if(p.engine==='audit')return select('year','年份',[['all','全部年份'],...Array.from({length:7},(_,i)=>String(2012+i))],c.year)+select('method','统计口径',[['unique','按小时去重'],['raw','按原始行权重']],c.method);
 if(p.engine==='forecast')return select('horizon','预测跨度（小时）',['1','3','6'],c.horizon)+select('model','模型',Object.entries(MODEL_NAMES),c.model)+select('month','练习测试月份',[['all','7至9月'],['07','7月'],['08','8月'],['09','9月']],c.month)+select('period','时段',[['all','全天'],['peak','高峰'],['offpeak','非高峰']],c.period);
 if(p.engine==='hotspots')return select('cell','网格边长（米）',['250','500','1000'],c.cell)+select('weight','排序依据',[['count','事故次数'],['injured','伤者人数']],c.weight)+select('borough','行政区',[['all','全部'],['MANHATTAN','曼哈顿'],['BROOKLYN','布鲁克林'],['QUEENS','皇后区'],['BRONX','布朗克斯'],['STATEN ISLAND','斯塔滕岛'],['UNKNOWN','未知']],c.borough);
 if(p.engine==='taxi')return select('day','日期类型',[['all','全部'],['weekday','平日'],['weekend','周末']],c.day)+select('period','时段',[['all','全天'],['night','夜间22—05时'],['day','白天06—21时']],c.period)+select('normalize','展示口径',[['daily','每日日均'],['total','累计总量']],c.normalize);
 return number('line','计数线x（米）',-20,55,1,c.line)+select('direction','方向',[['both','双向'],['positive','+x'],['negative','-x']],c.direction)+select('stride','采样帧间隔',['1','5','10'],c.stride)+number('band','单侧死区（米）',0,3,.1,c.band)+number('gap','最大间隔（秒）',.1,5,.1,c.gap)+select('type','类别',[['all','全部'],...data.meta.types],c.type);
}
function codeTab(p){return `${learningPanel(p)}${videoPanel(p)}<h2>补充对照与原有在线实验</h2><p>在线部分用于理解数据与方法；Python源码和工作本用于完整复现、修改模型和写出自己的分析。</p><div class="notebook-card"><div class="notebook-icon">.ipynb</div><div><h3>第${p.chapter}章 · 逐步实验工作本</h3><p>八章主工作本现已逐格组织；下方保留旧实验用于补充比较。</p></div><a class="button outline" href="chapters/notebooks/${p.id}.ipynb" download>下载工作本</a></div>${p.engine==='design'?`<section class="article-section"><h3>比较真实数据源</h3><p>选择场景后，分析资料能够支持什么、还缺什么。</p><div class="source-options">${SOURCE_CARDS.map((s,i)=>`<button data-source="${i}" class="outline">${s[0]}</button>`).join('')}</div><div id="source-detail"></div></section>`:`<section class="article-section"><div class="section-heading"><h3>在线对照实验</h3><span class="pill">真实数据 · 本机计算</span></div><form id="config-form" class="controls">${controls(p)}</form><div id="result" aria-live="polite"></div><div class="actions"><button id="save-experiment">保存对照记录</button><button class="outline" id="download-result">导出分析结果</button><span class="tiny" id="experiment-feedback" role="status"></span></div><p class="tiny">保存的记录会写入报告；不同配置不合并为排行榜。${p.id==='ch04'||p.id==='ch06'?'模型训练在Python完成，网页仅重算预先生成预测的误差。':''}</p></section>`}<section class="article-section"><h3>本地运行与修改</h3><p>先解压八章资料包，在解压后的根目录运行。Python依赖安装不会由网页自动执行。</p><pre class="command">${esc(command(p))}</pre><div class="actions"><a href="chapters/chapter-projects.zip" download>下载完整资料包</a><a href="chapters/README.md">环境与目录说明</a></div>${p.code?`<details id="source-code-details"><summary>阅读参考源码（Python）</summary><p><a href="${p.code}" target="_blank">打开完整源码 ↗</a></p><pre id="source-code">展开后读取。</pre></details>`:''}</section><section class="article-section"><h3>深入实践</h3>${ul(p.extensions)}</section>`;}
function command(p){const install='python -m pip install -r projects/python/requirements.txt';if(p.id==='ch01')return 'jupyter notebook chapters/notebooks/ch01.ipynb';if(p.id==='ch02')return 'python chapters/python/ch02_cleaning.py';if(p.id==='ch03')return 'python chapters/python/ch03_inference.py --n 60 --seed 42';if(p.id==='ch04')return install+'\npython chapters/python/ch04_regression.py';return `python projects/python/analyze.py --project ${p.engine}`+(['ch05','ch07','ch08'].includes(p.id)?`\n${install}\npython projects/python/extensions.py --project ${p.engine}`:'\n# 重新准备数据与训练模型\n'+install+'\npython projects/python/prepare_data.py --output projects/data');}
function stats(m){return `<div class="stats">${Object.entries(m).map(([k,v])=>`<div><small>${esc(k)}</small><strong>${fmt(v)}</strong></div>`).join('')}</div>`;}
function line(r){const series=r.series,max=Math.max(1,...series.flatMap(s=>s.values.filter(x=>x!=null))),w=800,h=260,L=64,R=18,T=20,B=44,n=r.labels.length,x=i=>L+i*(w-L-R)/Math.max(1,n-1),y=v=>h-B-v/max*(h-T-B);return `<div class="plot-scroll"><svg class="line-plot" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(r.unit)}"><title>${esc(r.unit)}</title>${[0,.25,.5,.75,1].map(a=>`<line x1="${L}" x2="${w-R}" y1="${y(max*a)}" y2="${y(max*a)}" stroke="#e8eaed"/><text x="${L-8}" y="${y(max*a)+5}" text-anchor="end">${Math.round(max*a)}</text>`).join('')}${series.map((s,k)=>{let active=false;const d=s.values.map((v,i)=>{if(v==null){active=false;return '';}const c=active?'L':'M';active=true;return c+x(i).toFixed(1)+','+y(v).toFixed(1);}).join(' ');return `<path d="${d}" fill="none" stroke="${k?'#d7863b':'#2388ba'}" stroke-width="2.2"/>`;}).join('')}${[0,Math.floor(n/2),n-1].map((i,j)=>`<text x="${x(i)}" y="${h-10}" text-anchor="${j===0?'start':j===2?'end':'middle'}">${esc(r.labels[i])}</text>`).join('')}</svg></div><div class="legend">${series.map((s,i)=>`<span><i style="background:${i?'#d7863b':'#2388ba'}"></i>${esc(s.name)}</span>`).join('')}</div>`;}
function histogram(values){const min=values[0],max=values.at(-1),bins=Array(24).fill(0),step=(max-min||1)/24;values.forEach(v=>bins[Math.min(23,Math.floor((v-min)/step))]++);const height=Math.max(...bins,1);return `<div class="plot-scroll"><svg class="line-plot" viewBox="0 0 800 250" role="img" aria-label="Bootstrap均值分布"><title>Bootstrap均值分布，横轴辆/小时，纵轴重采样次数</title>${bins.map((n,i)=>`<rect x="${52+i*29}" y="${205-n/height*170}" width="25" height="${n/height*170}" fill="#9976b1"><title>${Math.round(min+i*step)}至${Math.round(min+(i+1)*step)}：${n}次</title></rect>`).join('')}<text x="52" y="235">${Math.round(min)} 辆/小时</text><text x="748" y="235" text-anchor="end">${Math.round(max)} 辆/小时</text><text x="52" y="20">重采样均值分布 · 最大柱频数 ${height}</text></svg></div>`;}
function heatmap(r){const max=Math.max(1,...r.matrix.flat());return `<div class="table-scroll"><table class="heatmap"><caption>${esc(r.unit)}</caption><thead><tr><th>地区/时</th>${r.hours.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${r.matrix.map((row,i)=>`<tr><th>${r.rowLabels[i]}</th>${r.hours.map(h=>`<td style="background:rgba(64,158,189,${.06+.55*row[h]/max})">${fmt(row[h])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function space(r){if(!r.cells.length)return '<p class="empty">当前条件没有有效空间点。</p>';const minX=Math.min(...r.cells.map(c=>c.col)),maxX=Math.max(...r.cells.map(c=>c.col))+1,minY=Math.min(...r.cells.map(c=>c.row)),maxY=Math.max(...r.cells.map(c=>c.row))+1,s=Math.min(700/(maxX-minX),290/(maxY-minY)),max=Math.max(1,...r.cells.map(c=>c[config(current).weight]));return `<div class="plot-scroll"><svg class="space-plot" viewBox="0 0 800 350" role="img" aria-label="真实事故网格，不是道路底图"><title>事故记录网格，原点和投影说明见下方</title>${r.cells.map(c=>`<rect x="${50+(c.col-minX)*s}" y="${320-(c.row-minY+1)*s}" width="${Math.max(1,s-.2)}" height="${Math.max(1,s-.2)}" fill="#b77341" opacity="${.15+.85*c[config(current).weight]/max}"><title>网格${c.id}：${c.count}起；伤者${c.injured}人</title></rect>`).join('')}<text x="50" y="345">局部近似米制网格 · ${r.size}米 · 非风险图/非道路底图</text></svg></div>`;}
function run(){stop();try{const p=current,c=config(p);if(p.engine==='inference'){const r=bootstrap(data.rows,c);analysis={metrics:{抽样日期:r.n_days,样本均值:r.estimate,区间下限:r.lower,区间上限:r.upper},columns:['统计量','数值'],rows:[['可用日期',r.available_days],['完整观测日期参考均值',r.observed_reference],['区间宽度',r.upper-r.lower],['随机种子',r.seed],['重复次数',r.repetitions]],unit:'日内07、08、09时平均交通量，辆/小时。',note:'日级百分位Bootstrap以日期为重采样单位，依赖近似独立等假设。参考均值只代表本文件完整观测日期，不代表所有道路或未来年份。',exportColumns:['estimate','lower','upper','n_days'],exportRows:[[r.estimate,r.lower,r.upper,r.n_days]],histogram:r.bootstrap_means};}else analysis=p.engine==='bike'?bike(data,c):ENGINES[p.engine](data,c);const r=analysis;$('#result').innerHTML=stats(r.metrics)+`<p class="tiny">${esc(r.unit)}</p>`+(r.series?line(r):r.histogram?histogram(r.histogram):r.matrix?heatmap(r):p.engine==='hotspots'?space(r):`<div id="replay"></div><div class="replay-controls"><button id="play" class="outline">播放轨迹</button><label for="replay-time">回放时刻 <output id="time-label">0秒</output></label><input id="replay-time" type="range" min="0" max="119.9" step="0.1" value="0"></div>`)+`<p class="analysis-note">${esc(r.note)}</p>`+table(r.columns,r.rows,12);if(p.engine==='counting')replay(0);$('#experiment-feedback').textContent='已按当前参数计算。';}catch(e){analysis=null;$('#result').innerHTML=`<p class="notice error">${esc(e.message)}</p>`;}}
function replay(t){if(!analysis||!$('#replay'))return;const points=analysis.replayRows.filter(r=>r[1]<=t*1000&&r[1]>t*1000-1500),latest=new Map();for(const r of points)latest.set(r[0],r);const scale=6.5,x=v=>130+(v+23)*scale,y=v=>365-(v+11)*scale,band=+config(current).band;$('#replay').innerHTML=`<div class="plot-scroll"><svg class="space-plot" viewBox="0 0 800 430" role="img" aria-label="SinD真实平滑轨迹回放"><title>平滑轨迹，非原视频；坐标单位为米</title><rect x="${x(analysis.line-band)}" y="15" width="${band*2*scale}" height="360" fill="#f0d9bf"/><line x1="${x(analysis.line)}" x2="${x(analysis.line)}" y1="15" y2="375" stroke="#b57632" stroke-width="2"/>${[...latest.values()].map(([id,ms,px,py,type])=>`<circle cx="${x(px)}" cy="${y(py)}" r="4.5" fill="${['car','bus'].includes(type)?'#2f85a6':'#9666a8'}"><title>${esc(id)} · ${type}</title></circle><text x="${x(px)+6}" y="${y(py)-6}">${esc(id)}</text>`).join('')}<text x="32" y="401">x方向向右 · 地面坐标（米） · ${latest.size}个当前ID</text><text x="32" y="421">${t.toFixed(1)}秒 · 已触发${analysis.rows.filter(r=>r[1]<=t).length}次事件（非视频帧识别准确率）</text></svg></div>`;$('#time-label').textContent=t.toFixed(1)+'秒';}
function design(index=0){const s=SOURCE_CARDS[index];$('#source-detail').innerHTML=`<div class="source-detail"><h3>${s[0]} / ${s[1]}</h3><dl><dt>观测什么</dt><dd>${s[2]}</dd><dt>覆盖范围</dt><dd>${s[3]}</dd><dt>不能直接推断</dt><dd>${s[4]}</dd></dl><a href="${s[5]}" target="_blank" rel="noopener">查看官方数据说明 ↗</a><p>思考：你的任务需要的变量，是否真的包含在这些观测之中？</p></div>`;}
function evaluation(p){let compare='';if(p.id==='ch04'){compare=`<h3>旧协议补充：原回归基线</h3><p>训练2011年；验证2012年1至6月；公开练习测试2012年7至12月，共4,376行。各模型只在验证集选择其正则参数。</p>${table(['方法','验证RMSE','练习测试RMSE','练习测试MAE','alpha'],data.models.map(m=>[m.name,m.validation.RMSE,m.test.RMSE,m.test.MAE,m.alpha??'不适用']))}`;}if(p.id==='ch06'){const r=ENGINES.forecast(data,{...DEFAULTS.forecast,horizon:'1',period:'all',month:'all'});compare=`<h3>旧协议补充：1小时基线结果</h3><p>这不是当前主实验。旧方法在相同2,190条记录上比较；主实验统一采用2,169个1/3/6小时共同目标，两表不可直接排名。下表来自可复现脚本，不是学生排行榜。</p>${table(r.columns,r.rows)}`;}return `${primaryEvaluation(p)}<h2>补充实验的评价说明</h2><p class="question">${p.metric}</p>${compare?`<div class="notice neutral">公开练习自测可用于检查方法和文件，不应通过反复试探测试标签来调参。</div><section class="article-section">${compare}<h3>指标定义</h3><div class="formula">RMSE = √[Σ(预测值 − 实测值)² / n]<br>MAE = Σ|预测值 − 实测值| / n</div><p>n为按ID对齐的有效样本数。RMSE对较大误差更敏感；平均预测偏差保留正负号，反映整体高估或低估。各指标单位与目标相同。</p></section>`:'<div class="notice neutral">本项目不适合仅以单一分数排序。格式核查只检查文件组织，教师仍需审阅方法、证据与结论。</div>'}<section class="article-section"><h3>最低验收要求</h3>${ul(p.acceptance)}</section><section class="article-section"><h3>建议的评价量规</h3>${table(['维度','参考权重','重点'],[['问题与数据口径','20%','观测单元、范围、许可与数据适配'],['方法与对照','25%','基线、公平对照、参数和处理规则'],['证据与解释','25%','可复核结果、失败分析与不确定性'],['复现与表达','20%','代码、配置、数据版本与报告一致'],['适用边界','10%','偏差、隐私、未支持的推断']],10)}<p class="tiny">以上是教学建议，不是已确定的学校考核制度。网页不会自动折算课程成绩。</p></section>`;}
function submissionScope(p){return {ch01:'方案报告需包含研究问题、数据方案、指标定义、局限与许可四个标题；自动检查结构，不判断内容正确性。',ch02:'提交完整的40,575个不同小时，表头local_time,volume；与公开参考清洗口径比较。还应提交处理代码和质量审计报告。',ch03:'提交1行区间结果。CSV无法证明抽样方法正确，请附n、种子、重复次数、日期类型及代码。',ch04:'必须覆盖4,376个测试ID，预测cnt为非负有限数值。不得遗漏、重复或使用未知ID；RMSE单位为次/小时。',ch05:'提交至少3个候选网格及选择理由。为统一核查接口，ID取全部行政区、500米固定网格；其他尺度对照另附分析结果。',ch06:'自动自测接口固定为1小时、2018年7至9月、全部时段的2,190个ID。3/6小时任务与高峰子组作为报告中的深入对照，不混用提交ID。',ch07:'固定提交全月、全天、每日日均的7地区×24小时矩阵，共168行，地区使用英文源标签。其他归一化与时段对照另附配置。',ch08:'提交逐条事件（track_id,time_s,direction）。时间范围0至120秒，方向+x/-x；每ID每方向最多一次。没有独立真值，网页不报告计数准确率。'}[p.id];}
function history(p){const rows=record(p).history.slice().reverse();return rows.length?table(['时间','类型','结果'],rows.map(r=>[r.time,r.kind==='primary'?'主实验自测':r.kind==='comparison'?'专题对照：'+(r.config?.title||''):r.kind==='experiment'?'参数实验':'文件自测',Object.entries(r.metrics).filter(([,v])=>typeof v==='number'&&Number.isFinite(v)).map(([k,v])=>k+': '+fmt(v)).join('；')]),10):'<p class="empty">尚无记录。可以先在代码页保存一次对照实验。</p>';}
function submission(p){const r=record(p);return `${primarySubmission(p)}<h2>${p.chapter>=4?'补充旧协议CSV自测':'提交作品与本机自测'}</h2><p>将成果文件导入本页，检查格式${['ch04','ch06'].includes(p.id)?'并计算公开练习集误差':''}。文件只在当前浏览器读取，不发送到服务器；正式作业仍由教师指定的教学平台接收。</p><div class="notice">${submissionScope(p)}</div><section class="article-section"><h3>文件格式</h3><p><strong>${p.format}</strong></p><pre>${esc(p.sample||(p.id==='ch04'?'id,cnt\n（每个测试ID一行，共4376行）':'id,volume\n（每个1小时测试ID一行，共2190行）'))}</pre><div class="actions"><button class="outline" id="sample">下载提交模板</button><a href="chapters/${p.id}_report.md" download>下载报告模板</a></div><label class="upload-zone" for="submission-file"><strong>选择本地${p.id==='ch01'?'Markdown报告':'CSV成果'}文件</strong><span>${p.id==='ch01'?'不超过200KB':'不超过6MB'} · 不上传服务器</span><input id="submission-file" type="file" accept="${p.id==='ch01'?'.md,text/markdown':'.csv,text/csv'}"></label><div id="submission-status" role="status"></div></section><section class="article-section"><h3>我的本机记录</h3><p>最近10条实验或自测记录，只有这台浏览器可见。项目之间的结果不混排。</p><div id="history">${history(p)}</div></section><section class="article-section"><h3>整理项目报告</h3><p>这里填写结论与反思；概述页的阶段记录、实验配置和自测结果会一同导出。</p><label>报告正文<textarea id="report" maxlength="200000" rows="9" placeholder="研究问题、数据、方法与对照、结果、局限、复现方式。">${esc(r.report)}</textarea></label><div class="actions"><button id="export-report">导出报告 Markdown</button><button class="outline" id="export-records">导出本机记录 JSON</button></div></section>`;}
function rules(p){return `<h2>项目规则与学习约定</h2><section class="article-section"><h3>过程与成果</h3>${ul(['个人或小组完成，按教师实际教学安排组织，不设置虚构的截止日期或参赛人数。','可以使用开放工具与生成式AI辅助，但必须能解释代码、确认数据来源，并说明工具参与的部分。','不要把参考输出当作自己的独立结果；应提交具体对照、改进或失败分析。','报告、配置、数据与代码应能够相互对应。'])}</section><section class="article-section"><h3>数据许可与责任</h3><p>${p.source.license}。</p>${ul(p.boundaries)}<p>课程代码许可不覆盖第三方数据。特别是SinD数据采用禁止商业使用的自定义条款，不应称为标准CC0。</p><a href="chapters/DATA_SOURCES.md">来源与许可明细</a></section><section class="article-section"><h3>本机功能边界</h3>${ul(['无需注册；不收集姓名、学号和作品内容。','没有班级后台、云端Python训练或跨学生排行榜。','公开自测不具备防作弊和隐藏标签隔离能力，不能直接用于高利害考试。','本机存储可能被浏览器清理，请导出自己的报告和记录。'])}</section>`;}
function casesPage(chapter='all'){const chosen=chapter==='all'?CASES:CASES.filter(c=>c.chapter===+chapter);main.innerHTML=`<section class="page-intro"><p class="eyebrow">案例库 / 与章节项目配套</p><h1>围绕交通工程问题，开展完整研究。</h1><p>16篇论文式案例，围绕道路调查、运行预测、交通安全、共享单车与出租车运营、交叉口通行统计展开。包含摘要、研究区域、工程指标、方法、实证结果、应用讨论与参考资料，可配合在线对照实验复算。</p></section><div class="case-filters" aria-label="按章节筛选案例"><a href="#cases" class="${chapter==='all'?'selected':''}">全部案例</a>${PROJECTS.map(p=>`<a href="#cases/${p.chapter}" class="${+chapter===p.chapter?'selected':''}">第${p.chapter}章</a>`).join('')}</div><div class="section-heading"><h2>${chapter==='all'?'全部案例':'第'+esc(chapter)+'章案例'}</h2><span>${chosen.length}个案例</span></div><div class="case-grid">${chosen.map(caseCard).join('')}</div>`;}
function casePage(c){const p=PROJECTS.find(p=>p.chapter===c.chapter),target=PROJECTS.find(p=>p.id===c.target);main.innerHTML=renderCaseStudy(c,p,target,state.caseNotes[c.id]||'');}
function resources(){main.innerHTML=`<section class="page-intro"><p class="eyebrow">开放课程资源</p><h1>教材、实践与案例相互配合。</h1><p>教材负责概念与方法，章节项目负责完成任务，案例库负责形成从交通问题到工程结论的完整研究。</p></section><div class="resource-grid">${[['八章实践资料包','8份工作本、任务书、真实数据、参考代码、报告模板。','chapters/chapter-projects.zip'],['第一章交互课堂','保留已有第一章教学网页与课件。','chapter-01/'],['方法工具箱','按需复习原有小实验；注意历史数据来源标记。','methods.html'],['旧版项目记录','保留上一版五项目入口和该版本的本机记录。','project-archive.html'],['使用与环境说明','Python环境、运行命令与资料包结构。','chapters/README.md'],['数据来源与许可','处理链路、版权许可与研究范围。','chapters/DATA_SOURCES.md']].map(([h,d,url])=>`<article class="resource-card"><h2>${h}</h2><p>${d}</p><a href="${url}">打开资源 →</a></article>`).join('')}</div>`;}
function download(name,content,type='text/plain;charset=utf-8'){const u=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function save(p,kind,metrics,configValue={}){const r=record(p);r.history.push({time:new Date().toISOString(),kind,metrics,protocol:kind==='primary'?p.protocol.id:'legacy-supplement-v1',config:configValue,sourceFiles:(files?.[p.id]?.files||[]).map(f=>({path:f.path,sha256:f.sha256}))});r.history=r.history.slice(-10);persist();}
function report(p){const r=record(p),titles=p.id==='ch01'?['研究问题','数据方案','指标定义','局限与许可']:p.tasks.map(t=>t[0]);return [`# ${p.title}：项目报告`,'','> 本机草稿；自测记录不代表教师验收。',`主实验协议：${p.protocol.id}`,`主实验样本：${p.protocol.population}`,`主实验比较：${p.protocol.comparison}`,`必做方法：${p.protocol.required.join('；')}`,`工程交付：${p.protocol.deliverables.join('；')}`,`数据来源：${p.source.url}`,`许可：${p.source.license}`,'',...titles.flatMap((title,i)=>['## '+title,'',r.notes[i]||'待填写','']),'## 报告正文','',r.report||'待填写','','## 对照与自测记录','','```json',JSON.stringify(r.history,null,2),'```','','## 提交检查',...p.acceptance.map(x=>'- [ ] '+x)].join('\n');}
async function reference(p){if(p.id==='ch02')return get('projects/data/audit.json');if(p.id==='ch04'){const d=await projectData(p);return {rows:d.rows.map(r=>[r[0],r[3]])};}if(p.id==='ch06')return get('chapters/data/ch06_scoring.json');if(p.id==='ch05'){const d=await projectData(p);return {ids:ENGINES.hotspots(d,DEFAULTS.hotspots).rows.map(r=>r[0])};}if(p.id==='ch08'){const d=await projectData(p);return {ids:d.rows.map(r=>String(r[0]))};}return {};}
async function sample(p){if(p.id==='ch04'||p.id==='ch06'){const path=p.id==='ch04'?'chapters/data/ch04_mean_submission.csv':'chapters/data/ch06_sample_submission.csv';download(p.id+'_sample_submission.csv',await get(path,'text'),'text/csv;charset=utf-8');return;}if(p.id==='ch05'){const ref=await reference(p);download(p.id+'_sample_submission.csv',toCSV(p.header,ref.ids.slice(0,3).map(id=>[id,'请填写具体选择理由'])));return;}download(p.id+(p.id==='ch01'?'_proposal.md':'_sample_submission.csv'),p.sample);}
async function route(){const hash=location.hash.slice(1)||'projects';if(hash==='content')return;const seq=++token;stop();current=null;data=null;analysis=null;currentTab='';$('#sidebar').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');let [kind,id,tab='overview']=hash.split('/');if(kind==='project'&&ALIASES[id]){const mapped={workbench:'code',brief:'overview',stages:'overview',rubric:'evaluation',submission:'submission',data:'data'}[tab]||'overview';location.replace(href(ALIASES[id],mapped));return;}try{if(kind==='project'){const p=PROJECTS.find(p=>p.id===id);if(!p||!TABS.some(t=>t[0]===tab))throw Error('未找到项目或栏目。');current=p;currentTab=tab;sidebar();main.innerHTML='<p class="loading" role="status">正在读取项目资料…</p>';files??=await get('chapters/data/files.json');let loaded=null;if(['code','evaluation'].includes(tab))loaded=await projectData(p);if(seq!==token)return;data=loaded;document.title=p.title+' · '+TABS.find(t=>t[0]===tab)[1];const content={overview:()=>overview(p),data:()=>dataTab(p),code:()=>codeTab(p),evaluation:()=>evaluation(p),submission:()=>submission(p),cases:()=>`<h2>本章案例</h2><p>阅读本章交通工程研究案例，核查问题、数据与指标，再用项目实验复算结果，形成自己的研究报告。</p><div class="case-grid inside">${CASES.filter(c=>c.chapter===p.chapter).map(caseCard).join('')}</div><a href="#cases">进入完整案例库 →</a>`,rules:()=>rules(p)}[tab]();main.innerHTML=heading(p,tab)+`<div class="content-columns"><article class="reading">${content}</article>${aside(p)}</div>`;mountLearning(main.querySelector('.reading'),p,save,download,()=>{if($('#history'))$('#history').innerHTML=history(p);});if(tab==='data')preview(p,0);if(tab==='code'){if(p.engine==='design')design();else{run();mountComparisons($('#config-form').closest('section'),p,data,r=>save(p,'comparison',r.metrics,{experimentId:r.id,title:r.title,parameters:r.config,protocol:r.protocol,columns:r.columns,rows:r.rows,source:r.source}),download);}const details=$('#source-code-details');if(details)details.addEventListener('toggle',async()=>{if(!details.open)return;try{const text=await get(p.code,'text');if(seq===token&&$('#source-code'))$('#source-code').textContent=text;}catch(e){if(seq===token&&$('#source-code'))$('#source-code').textContent=e.message;}});}}else{sidebar();document.title='交通数据挖掘 · '+(kind.includes('case')?'案例库':'章节实践');if(kind==='cases')casesPage(id||'all');else if(kind==='case'){const c=CASES.find(c=>c.id===id);if(!c)throw Error('未找到案例。');casePage(c);}else if(kind==='resources')resources();else if(kind==='search')home(decodeURIComponent(hash.slice(7)));else if(/^(lab|learn|start|open|ch0[3-8])$/.test(hash)){location.replace('methods.html#'+hash);return;}else home();}window.scrollTo(0,0);}catch(e){if(seq!==token)return;main.innerHTML=`<div class="notice error">${esc(e.message)}<p><button id="retry">重试</button> <a href="#projects">返回项目列表</a></p></div>`;}}
$('#search-form').addEventListener('submit',e=>{e.preventDefault();location.hash='search/'+encodeURIComponent($('#search').value.trim());});
$('#menu').addEventListener('click',()=>{const open=$('#sidebar').classList.toggle('open');$('#menu').setAttribute('aria-expanded',String(open));});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#sidebar').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');}});
main.addEventListener('input',e=>{if(current&&e.target.dataset.note!==undefined){record(current).notes[+e.target.dataset.note]=e.target.value;persist();$('#draft-status').textContent=storageOK?'阶段记录已保存到本机。':'请导出备份。';}if(e.target.id==='report'&&current){record(current).report=e.target.value;persist();}if(e.target.id==='case-note'){state.caseNotes[e.target.dataset.case]=e.target.value;persist();}if(e.target.id==='replay-time'){stop();if($('#play'))$('#play').textContent='播放轨迹';replay(+e.target.value);}});
main.addEventListener('submit',e=>e.preventDefault());
main.addEventListener('change',async e=>{if(current&&e.target.closest('#config-form')){if($('#config-form').reportValidity()){configs.set(current.id,Object.fromEntries(new FormData($('#config-form'))));run();}}if(e.target.id==='submission-file'&&current){const p=current,seq=token,file=e.target.files[0];if(!file)return;$('#submission-status').innerHTML='<p>正在本机检查…</p>';try{if(file.size>(p.id==='ch01'?200000:6000000))throw Error('文件超过本项目大小限制。');const text=await file.text(),ref=await reference(p);if(seq!==token)return;const result=validateSubmission(p,text,ref);save(p,'submission',result.metrics,{filename:file.name,validation:result.type});$('#submission-status').innerHTML=`<div class="notice success">${result.type==='score'?'自测完成':'检查完成'}：${esc(result.note)}</div>${stats(result.metrics)}`;$('#history').innerHTML=history(p);}catch(err){if(seq===token)$('#submission-status').innerHTML=`<div class="notice error">未通过检查：${esc(err.message)}</div>`;}}});
main.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(handleCaseStudyAction(b,CASES,download))return;if(b.id==='retry'){route();return;}if(b.dataset.file!==undefined&&current){preview(current,+b.dataset.file);return;}if(b.dataset.source!==undefined){design(+b.dataset.source);return;}if(b.id==='export-case'){const c=CASES.find(x=>x.id===b.dataset.case);download(c.id+'.md',`# ${c.title}\n\n来源：${c.source}\n\n## 我的分析\n\n${state.caseNotes[c.id]||'待填写'}`);return;}if(!current)return;const p=current;if(b.id==='start'){record(p).started=true;persist();location.hash=href(p,'data');}if(b.id==='save-experiment'&&analysis){save(p,'experiment',{...analysis.metrics},{...config(p)});$('#experiment-feedback').textContent='已保存；可在提交页查看并随报告导出。';}if(b.id==='download-result'&&analysis)download(p.id+'_analysis.csv',toCSV(analysis.exportColumns||analysis.columns,analysis.exportRows||analysis.rows),'text/csv;charset=utf-8');if(b.id==='export-report')download(p.id+'_report.md',report(p));if(b.id==='export-records')download(p.id+'_records.json',JSON.stringify({version:2,project:p.id,primaryProtocol:p.protocol,record:record(p)},null,2),'application/json');if(b.id==='sample'){b.disabled=true;try{await sample(p);}catch(err){if(current?.id===p.id&&$('#submission-status'))$('#submission-status').textContent=err.message;}finally{b.disabled=false;}}if(b.id==='play'){if(timer){stop();b.textContent='播放轨迹';}else{b.textContent='暂停';timer=setInterval(()=>{const s=$('#replay-time');if(!s){stop();return;}const t=(+s.value+.5)%120;s.value=t;replay(t);},250);}}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();if($('#play'))$('#play').textContent='播放轨迹';}});
function syncSidebar(){const side=$('#sidebar');side.inert=innerWidth<=960&&!side.classList.contains('open');}
$('#menu').addEventListener('click',syncSidebar);
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if($('#sidebar').contains(document.activeElement))$('#menu').focus();syncSidebar();}});
window.addEventListener('resize',syncSidebar);
window.addEventListener('hashchange',route);window.addEventListener('hashchange',syncSidebar);await route();syncSidebar();
import {videoPanel} from './video-learning.js';
