import {CASE_STUDIES} from './case-studies.js';
import {CASE_EVIDENCE,CASE_EVIDENCE_META} from './data/case-evidence.js';

export const CASE_SECTIONS=[['background','研究背景与意义'],['problem','问题分析与定义'],['method','解决思路与方法'],['evaluation','结果评价与分析']];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=v=>v==null?'无数据':typeof v==='number'?v.toLocaleString('zh-CN',{maximumFractionDigits:3}):String(v);
const paragraphs=rows=>rows.map(t=>`<p>${esc(t)}</p>`).join('');
const href=(p,tab='code')=>`#project/${p}/${tab}`;
function table(t){return `<div class="case-table-scroll"><table><caption>${esc(t.title)}</caption><thead><tr>${t.columns.map(c=>`<th scope="col">${esc(c)}</th>`).join('')}</tr></thead><tbody>${t.rows.map(r=>`<tr>${r.map(v=>`<td>${esc(number(v))}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${t.note?`<p class="tiny">${esc(t.note)}</p>`:''}`;}
export function renderCaseStudy(c,p,target,note){
 const s=CASE_STUDIES[c.id],e=CASE_EVIDENCE[c.id];
 const sourceFiles=e.files.map(path=>[path,CASE_EVIDENCE_META.files[path]]);
 const sections=CASE_SECTIONS.map(([key,title],i)=>{
  const body=key==='method'?`<ol class="case-method-steps">${s.method.map(([h,t])=>`<li><h3>${esc(h)}</h3><p>${esc(t)}</p></li>`).join('')}</ol>`:paragraphs(s[key]);
  const extra=key==='problem'?table({title:'任务定义与分析边界',columns:['要素','本案例定义'],rows:s.scope}):key==='evaluation'?`<div class="case-result-protocol"><strong>本页结果口径</strong><p>${esc(e.protocol)}</p><small>以下为固定快照的实际计算或材料核查；在线调参不会自动改写本页基准结论。</small></div>${e.tables.map(table).join('')}`:'';
  return `<section class="article-section case-section" id="case-${key}" tabindex="-1"><h2><span>${String(i+1).padStart(2,'0')}</span>${title}</h2>${key==='evaluation'?extra+body:body+extra}</section>`;
 }).join('');
 return `<div class="breadcrumbs"><a href="#cases">案例库</a><span>/</span><a href="#cases/${c.chapter}">第${c.chapter}章</a></div><header class="case-header"><p class="eyebrow">${esc(c.type)} · 第${c.chapter}章 · 完整教学案例</p><h1>${esc(c.title)}</h1><p>${esc(c.lead)}</p><div class="case-reading-meta"><span>4个分析环节</span><span>含结果表与口径说明</span><span>建议阅读与讨论 15—25分钟</span></div></header><div class="content-columns"><article class="reading case-reading"><div class="case-central-question"><small>贯穿本案例的问题</small><p>${esc(c.question)}</p><span>先写下判断，再检查问题定义、方法和结果是否支持它。</span></div><nav class="case-toc" aria-label="案例分析目录">${CASE_SECTIONS.map(([id,title],i)=>`<button type="button" class="outline" data-case-section="${id}"><span>${String(i+1).padStart(2,'0')}</span>${title}</button>`).join('')}</nav>${sections}<section class="case-conclusion"><h2>本案例的结论</h2><p>${esc(s.takeaway)}</p></section><section class="article-section"><h2>讨论与交付</h2><p>${esc(s.assignment)}</p><p class="tiny">复核顺序：问题是否可回答 → 变量与单位是否明确 → 对照是否公平 → 结果能否复现 → 结论是否越过证据。</p><label>我的案例笔记<textarea id="case-note" data-case="${c.id}" maxlength="20000" placeholder="按背景、问题、方法、评价四个方面整理你的分析，写出数据依据和仍需验证的判断。">${esc(note)}</textarea></label><div class="actions"><button class="outline" id="export-case" data-case="${c.id}">导出案例笔记</button><button type="button" class="outline" data-download-study="${c.id}">下载案例全文 Markdown</button></div></section><details class="case-provenance"><summary>资料来源、计算口径与复现</summary><p><a href="${esc(c.source)}" target="_blank" rel="noopener">查看官方数据来源 ↗</a>${(s.references||[]).map(([title,url])=>` · <a href="${esc(url)}" target="_blank" rel="noopener">${esc(title)} ↗</a>`).join('')}</p><p>案例场景与分析为课程原创教学内容，不代表管理部门已实施的研究或治理成果。结果由课程固定数据快照生成；提出但尚未实施的研究设计不作为实证结论。</p>${table({title:'本案例使用的文件及SHA-256',columns:['文件','SHA-256'],rows:sourceFiles})}<p><a href="chapters/build-case-evidence.mjs">证据表生成代码</a> · <a href="chapters/DATA_SOURCES.md">数据处理与许可</a> · <a href="chapters/CASEBOOK.md" download>下载完整16案例册</a></p>${c.id==='similar-days'?'<p>聚类原始输出：<a href="chapters/data/case-cluster-comparison.csv">类别数对照</a> · <a href="chapters/data/case-day-clusters-4.csv">K=4日期分组</a> · <a href="chapters/data/case-cluster-centers-4.csv">K=4中心向量</a>。使用现有Python扩展代码复算，版本与参数见本页口径。</p>':''}<p class="tiny">课程代码许可不覆盖第三方数据；SinD须遵循提供方包含禁止商业使用条款的原许可。</p></details></article><aside class="project-aside"><h3>对应实践</h3><p>第${target.chapter}章 · ${esc(target.title)}</p><a class="button" href="${href(c.target)}">打开对应实验</a><section class="article-section"><h3>带着问题做对照</h3><p>${esc(s.experiment.label)}</p><a class="button outline" href="${href(s.experiment.project)}/${s.experiment.id}">打开配套专题</a><p class="tiny">专题按默认参数打开。先复核基准，再修改条件，不把调参结果与本文固定口径混用。</p></section><section class="article-section"><h3>阅读资料</h3><a href="chapters/CASEBOOK.md" download>下载完整案例册</a><p class="tiny">网页、单篇下载与案例册采用同一份内容和结果表。</p></section><a href="${href(p.id,'cases')}">查看本章全部案例 →</a></aside></div>`;
}
const mdCell=v=>number(v).replaceAll('|','\\|').replaceAll('\n',' ');
const mdTable=t=>['',`**${t.title}**`,'','| '+t.columns.map(mdCell).join(' | ')+' |','| '+t.columns.map(()=>'---').join(' | ')+' |',...t.rows.map(r=>'| '+r.map(mdCell).join(' | ')+' |'),'',t.note||'',''].join('\n');
export function caseToMarkdown(c){
 const s=CASE_STUDIES[c.id],e=CASE_EVIDENCE[c.id];
 return [`# 第${c.chapter}章 · ${c.title}`,'',c.lead,'',`核心问题：${c.question}`,'',...CASE_SECTIONS.flatMap(([key,title])=>[`## ${title}`,'',...(key==='method'?s.method.map(([h,t],i)=>`${i+1}. **${h}**：${t}`):key==='evaluation'?[`结果口径：${e.protocol}`,'',...e.tables.map(mdTable),...s.evaluation.flatMap(t=>[t,''])]:s[key].flatMap(t=>[t,''])),'',...(key==='problem'?[mdTable({title:'任务定义与分析边界',columns:['要素','本案例定义'],rows:s.scope})]:[])]),'## 结论与讨论','',s.takeaway,'',s.assignment,'','## 资料与复现','',`[官方数据来源](${c.source})`,...(s.references||[]).map(([title,url])=>`[${title}](${url})`),'',`[配套专题：${s.experiment.label}](https://lilinchao.github.io/traffic-book-practice/open-course/#project/${s.experiment.project}/code/${s.experiment.id})`,'','固定快照与处理链路见DATA_SOURCES.md。计算或材料核查不代表独立真值验证；尚未实施的方案不作为既有成果。','',...e.files.map(path=>`- ${path}：SHA-256 ${CASE_EVIDENCE_META.files[path]}`),'',c.id==='similar-days'?'聚类通过projects/python/extensions.py --project taxi复算；scikit-learn 1.9.1，random_state=42，n_init=10。详细输出见chapters/data/case-*.csv。':'',''].join('\n');
}
export function handleCaseStudyAction(button,cases,download){
 if(button.dataset.caseSection){const section=document.getElementById('case-'+button.dataset.caseSection);if(section){section.focus({preventScroll:true});section.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}return true;}
 if(button.dataset.downloadStudy){const c=cases.find(c=>c.id===button.dataset.downloadStudy);if(c)download(c.id+'_case.md',caseToMarkdown(c));return true;}
 return false;
}
